" Note: Skip initialization for vim-tiny or vim-small.
if 1
	"execute 'source' fnamemodify(expand('<sfile>'), ':h').'/config/vimrc'
  execute 'source' '/home/kyrisu/.dotfiles/nvim/config/vimrc'
endif
